version: "3.8"

services:
  file_server:
    build:
        context: file_server/
    ports:
      - "1234"
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: "0.25"
      replicas: 4
    volumes:
      - ./.fileserver/data:/tmp/

#   Add more container definitions below
  proxy:
    container_name: proxy
    build:
      context: proxy/
    ports:
      - "8080"
    environment:
      - FILE_SERVER_HOST=file_server
      - FILE_SERVER_PORT=1234
      - PROXY_MODE=simple
    deploy:
      resources:
        limits:
          memory: 512MB
          cpus: "1"
      replicas: 1

  # LOAD TESTER:
  # This container is for convenience and does not count against your resource cap.
  # Comment this out if you want to manually run load tests from the `load_test` directory.
  go_load_tester:
    container_name: load-tester
    build:
      context: go_load_test/
    environment:
      - FILE_SERVER_HOST=file_server            # Point this to your application middleware (port will change)
      - FILE_SERVER_PORT=1234                   # Point this to your application middleware (port will change)
      - FILE_SERVER_PROTO=http                  # Point this to your application middleware (port will change)
      - FILE_SERVER_PATH_PREFIX=api/fileserver  # Point this to your application middleware (port will change)
      - REQUESTS_PER_SECOND=1                   # Bases requests/sec the load test will begin on.
      - SEED_GROWTH_AMOUNT=0                    # Every second, this many more requests will be scheduled
      - MAX_FILE_COUNT=5000                     # Recommend 2-5x REQUESTS_PER_SECOND
      - MAX_FILE_SIZE=512                       # 1KB, but could be set to ANYTHING in live tests
      - TERM=xterm-256color
    volumes:
      - ./.fileserver/data:/tmp/  # Error logs are written to this data dir under load_test.log
    depends_on:
      - file_server

#  python_load_tester:
#    container_name: load-tester
#    build:
#      context: python_load_test/
#    environment:
#      - FILE_SERVER_ADDR=http://file_server:1234  # Point this to your application middleware (port will change)
#      - REQUESTS_PER_SECOND=95
#      - MAX_FILE_COUNT=200       # Recommend 2-5x REQUESTS_PER_SECOND
#      - MAX_FILE_SIZE=1024       # 1KB, but could be set to ANYTHING in live tests
#      - TERM=xterm-256color
#    volumes:
#      - ./.fileserver/data:/tmp/  # Error logs are written to this data dir under load_test.log
#    depends_on:
#      - file_server