version: "3.8"

services:
  file_server_1:
    build:
        context: file_server/
    ports:
      - "1234:1234"
    deploy:
      resources:
        limits:
          memory: 64M
          cpus: "0.25"
      replicas: 1
    volumes:
      - ./.fileserver/data:/tmp/

  file_server_2:
    build:
        context: file_server/
    ports:
      - "1235:1234"
    deploy:
      resources:
        limits:
          memory: 64M
          cpus: "0.25"
      replicas: 1
    volumes:
      - ./.fileserver/data:/tmp/

  file_server_3:
    build:
        context: file_server/
    ports:
      - "1236:1234"
    deploy:
      resources:
        limits:
          memory: 64M
          cpus: "0.25"
      replicas: 1
    volumes:
      - ./.fileserver/data:/tmp/

  file_server_4:
    build:
        context: file_server/
    ports:
      - "1237:1234"
    deploy:
      resources:
        limits:
          memory: 64M
          cpus: "0.25"
      replicas: 1
    volumes:
      - ./.fileserver/data:/tmp/

#   Add more container definitions below
  proxy:
    container_name: proxy
    build:
      context: proxy/
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - FILE_SERVER_HOST=file_server_1,file_server_2,file_server_3,file_server_4
      - FILE_SERVER_PORT=1234,1234,1234,1234
      - FILE_SERVER_PROTO=http,http,http,http
      - PROXY_MODE=simple
    deploy:
      resources:
        limits:
          memory: 100M
          cpus: "1"
      replicas: 1
    volumes:
      - ./.fileserver/data:/tmp/
    depends_on:
      - file_server_1
      - file_server_2
      - file_server_3
      - file_server_4

  # LOAD TESTER:
  # This container is for convenience and does not count against your resource cap.
  # Comment this out if you want to manually run load tests from the `load_test` directory.
  go_load_tester:
    container_name: load-tester
    build:
      context: go_load_test/
    environment:
      - FILE_SERVER_HOST=proxy                  # Point this to your application middleware
      - FILE_SERVER_PORT=8080                   # Point this to your application middleware (port will change)
      - FILE_SERVER_PROTO=http                  # Point this to your application middleware
      - FILE_SERVER_PATH_PREFIX=api/fileserver
      - REQUESTS_PER_SECOND=1                   # Bases requests/sec the load test will begin on.
      - SEED_GROWTH_AMOUNT=3                    # Every second, this many more requests will be scheduled
      - MAX_FILE_COUNT=1000                     # Recommend 2-5x REQUESTS_PER_SECOND
      - MAX_FILE_SIZE=512                       # 1KB, but could be set to ANYTHING in live tests
      - TERM=xterm-256color
    volumes:
      - ./.fileserver/data:/tmp/  # Error logs are written to this data dir under load_test.log
    depends_on:
      - proxy

#  python_load_tester:
#    container_name: load-tester
#    build:
#      context: python_load_test/
#    environment:
#      - FILE_SERVER_ADDR=http://file_server:1234  # Point this to your application middleware (port will change)
#      - REQUESTS_PER_SECOND=95
#      - MAX_FILE_COUNT=200       # Recommend 2-5x REQUESTS_PER_SECOND
#      - MAX_FILE_SIZE=1024       # 1KB, but could be set to ANYTHING in live tests
#      - TERM=xterm-256color
#    volumes:
#      - ./.fileserver/data:/tmp/  # Error logs are written to this data dir under load_test.log
#    depends_on:
#      - file_server