version: "3.8"

services:
  file_server:
    build:
        context: .
    ports:
      - "1234"
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: "0.25"
      replicas: 1
    volumes:
      - ./.fileserver/data:/tmp/

  # Add more container definitions below

  # LOAD TESTER:
  # This container is for convenience and does not count against your resource cap.
  # Comment this out if you want to manually run load tests from the `load_test` directory.
  load_tester:
    container_name: load-tester
    build:
      context: load_test/
    environment:
      - FILE_SERVER_ADDR=http://file_server:1234  # Point this to your application middleware (port will change)
      - REQUESTS_PER_SECOND=100
      - MAX_FILE_COUNT=500       # Recommend 2-5x REQUESTS_PER_SECOND
      - MAX_FILE_SIZE=1024       # 1KB, but could be set to ANYTHING in live tests
      - TERM=xterm-256color
    volumes:
      - ./.fileserver/data:/tmp/  # Error logs are written to this data dir under load_test.log
    depends_on:
      - file_server